In [6]:
import pandas as pd
sumtotal=0
ltl_types = set()
import os
path2data = './processed_data/ConformalNL2LTL/'
data = os.listdir(path2data)
data = [x for x in data]
lista = []
for elem in data:
    df = pd.read_csv(path2data + '/' + elem, sep=';')
    df['source'] = 'ConformalNL2LTL'
    lista.append( df )
result = pd.concat(lista, ignore_index=True)

import re
def normalize_aps(formula):
    return re.sub(r'ap_\d+', 'prop', formula)

upper_limit=10


result['normalized_LTL_formula'] = result['lifted_LTL'].apply(normalize_aps)
result['normalized_LTL_formula'].value_counts().to_csv('dist/ConformalNL2LTL.csv')
result['lifted_lifted_LTL_formula'] = result['normalized_LTL_formula']
sumtotal += result['normalized_LTL_formula'].value_counts().clip(upper=upper_limit).sum()
ltl_types |= set(result['normalized_LTL_formula'].value_counts().index.tolist())

nested_dict={}
nested_dict2 = {
    source: result.groupby('normalized_LTL_formula').apply(
        lambda x: set(zip(x['original NL'], x['Spot LTL'], x['APs'], x['lifted_lifted_LTL_formula'], x['source']))
    ).to_dict()
    for source, result in result.groupby('source')
}
res1 =result
nested_dict = nested_dict2

In [7]:
path2data = './processed_data/NL to LTL Synthetic Dataset/'
data = os.listdir(path2data)
data = [x for x in data]
lista = []
for elem in data:
    df = pd.read_excel(path2data + '/' + elem)
    df['source'] = 'NL-to-LTL-Synthetic-Dataset' + elem.split('.')[0]
    lista.append( df )
result = pd.concat(lista, ignore_index=True)

def normalize_aps(formula):
    return re.sub(r'ap_\d+', 'prop', formula)


result['normalized_LTL_formula'] = result['lifted_LTL'].apply(normalize_aps)
result['normalized_LTL_formula'].value_counts().to_csv('dist/NL to LTL Synthetic Dataset.csv')
result['lifted_lifted_LTL_formula'] = result['normalized_LTL_formula']
sumtotal += result['normalized_LTL_formula'].value_counts().clip(upper=upper_limit).sum()
ltl_types |= set(result['normalized_LTL_formula'].value_counts().index.tolist())


nested_dict2 = {
    source: result.groupby('normalized_LTL_formula').apply(
        lambda x: set(zip(x['original NL'], x['Spot LTL'], x['APs'], x['lifted_lifted_LTL_formula'], x['source']))
    ).to_dict()
    for source, result in result.groupby('source')
}
res2 = result
for elem in nested_dict2:
    nested_dict[elem] = nested_dict2[elem]

In [8]:
path2data = './processed_data/NL2TL/'
data = os.listdir(path2data)
data = [x for x in data]
lista = []
for elem in data:
    df = pd.read_csv(path2data + '/' + elem, sep=';')
    lista.append( df )
result = pd.concat(lista, ignore_index=True)
import re
def normalize_aps(formula):
    return re.sub(r'ap_\d+', 'prop', formula)


result['normalized_LTL_formula'] = result['lifted_LTL'].apply(normalize_aps)
result['normalized_LTL_formula'].value_counts().to_csv('dist/VLTL-Bench_new.csv')
result['lifted_lifted_LTL_formula'] = result['normalized_LTL_formula']
sumtotal += result['normalized_LTL_formula'].value_counts().clip(upper=upper_limit).sum()
ltl_types |= set(result['normalized_LTL_formula'].value_counts().index.tolist())


nested_dict2 = {
    source: result.groupby('normalized_LTL_formula').apply(
        lambda x: set(zip(x['original NL'], x['Spot LTL'], x['APs'], x['lifted_lifted_LTL_formula'], x['source']))
    ).to_dict()
    for source, result in result.groupby('source')
}
res3= result
for elem in nested_dict2:
    nested_dict[elem] = nested_dict2[elem]

In [9]:
path2data = './processed_data/VLTL-Bench/new/'
data = os.listdir(path2data)
data = [x for x in data]
lista = []
for elem in data:
    df = pd.read_csv(path2data + '/' + elem, sep=';')
    df['source'] = 'VLTL-Bench_New'
    lista.append( df )
result = pd.concat(lista, ignore_index=True)
import re
def normalize_aps(formula):
    return re.sub(r'ap_\d+', 'prop', formula)


result['normalized_LTL_formula'] = result['lifted_LTL'].apply(normalize_aps)
result['normalized_LTL_formula'].value_counts().to_csv('dist/VLTL-Bench_new.csv')
result['lifted_lifted_LTL_formula'] = result['normalized_LTL_formula']
sumtotal += result['normalized_LTL_formula'].value_counts().clip(upper=upper_limit).sum()
ltl_types |= set(result['normalized_LTL_formula'].value_counts().index.tolist())


nested_dict2 = {
    source: result.groupby('normalized_LTL_formula').apply(
        lambda x: set(zip(x['original NL'], x['Spot LTL'], x['APs'], x['lifted_lifted_LTL_formula'], x['source']))
    ).to_dict()
    for source, result in result.groupby('source')
}
res4=result
for elem in nested_dict2:
    nested_dict[elem] = nested_dict2[elem]

In [10]:
path2data = './processed_data/VLTL-Bench/prev/'
data = os.listdir(path2data)
data = [x for x in data]
lista = []
for elem in data:
    df = pd.read_csv(path2data + '/' + elem, sep=';')
    df['source'] = 'VLTL-Bench_Prev'
    lista.append( df )
result = pd.concat(lista, ignore_index=True)
import re
def normalize_aps(formula):
    return re.sub(r'ap_\d+', 'prop', formula)


result['normalized_LTL_formula'] = result['lifted_LTL'].apply(normalize_aps)
result['normalized_LTL_formula'].value_counts().to_csv('dist/VLTL-Bench_prev.csv')
result['lifted_lifted_LTL_formula'] = result['normalized_LTL_formula']
sumtotal += result['normalized_LTL_formula'].value_counts().clip(upper=upper_limit).sum()
ltl_types |= set(result['normalized_LTL_formula'].value_counts().index.tolist())


nested_dict2 = {
    source: result.groupby('normalized_LTL_formula').apply(
        lambda x: set(zip(x['original NL'], x['Spot LTL'], x['APs'], x['lifted_lifted_LTL_formula'], x['source']))
    ).to_dict()
    for source, result in result.groupby('source')
}
res5=result
for elem in nested_dict2:
    nested_dict[elem] = nested_dict2[elem]

In [11]:
sumtotal

np.int64(6147)

In [12]:
len(ltl_types)

792

In [13]:
for elem in nested_dict:
    print(elem,  len(nested_dict[elem]))

ConformalNL2LTL 58
NL-to-LTL-Synthetic-Datasetprocessed_data 46
lifted_data_pureLTL.jsonl 626
VLTL-Bench_New 34
VLTL-Bench_Prev 174

In [135]:
dfs = [res1, res2, res3, res4, res5]

# Stack them vertically
combined_df = pd.concat(dfs, ignore_index=True)
combined_df

,original NL,original LTL,Spot LTL,APs,ap_NL,dict_AP,AP_lifted_dict,lifted_LTL,source,normalized_LTL_formula,lifted_lifted_LTL_formula
0,Take a picture of building 2,<>(building_2&&photo),F(building_2 & photo),"['photo', 'building_2']",Take a picture of building_2,"{'photo': 'photo', 'building 2': 'building_2'}","{'photo': 'ap_0', 'building_2': 'ap_1'}",F(ap_1 & ap_0),ConformalNL2LTL,F(prop & prop),F(prop & prop)
1,Take bottle 3 from store 1 and put it in hospi...,<>(shop_1&&<>(p_bottle_3&&<>(hospital_2&&pd))),F(shop_1 & F(p_bottle_3 & F(hospital_2 & pd))),"['pd', 'p_bottle_3', 'shop_1', 'hospital_2']",Take p_bottle_3 from store 1 and put it in hos...,"{'pd': 'pd', 'bottle 3': 'p_bottle_3', 'shop 1...","{'pd': 'ap_0', 'p_bottle_3': 'ap_1', 'shop_1':...",F(ap_2 & F(ap_1 & F(ap_3 & ap_0))),ConformalNL2LTL,F(prop & F(prop & F(prop & prop))),F(prop & F(prop & F(prop & prop)))
2,Go to parking lot 2 and pick up dish 2,<>(parking_lot_2&&p_dish_2),F(p_dish_2 & parking_lot_2),"['p_dish_2', 'parking_lot_2']",Go to parking_lot_2 and pick up p_dish_2,"{'dish 2': 'p_dish_2', 'parking lot 2': 'parki...","{'p_dish_2': 'ap_0', 'parking_lot_2': 'ap_1'}",F(ap_0 & ap_1),ConformalNL2LTL,F(prop & prop),F(prop & prop)
3,Go to hospital 3 and pick up water bottle 4 wh...,<>(hospital_3&&p_bottle_4)&&[]!pharmacy_2,F(hospital_3 & p_bottle_4) & G!pharmacy_2,"['p_bottle_4', 'hospital_3', 'pharmacy_2']",Go to hospital_3 and pick up water p_bottle_4 ...,"{'bottle 4': 'p_bottle_4', 'hospital 3': 'hosp...","{'p_bottle_4': 'ap_0', 'hospital_3': 'ap_1', '...",F(ap_1 & ap_0) & G!ap_2,ConformalNL2LTL,F(prop & prop) & G!prop,F(prop & prop) & G!prop
4,Stay in parking lot 4 until you reach car 5,parking_lot_4 U car_5,parking_lot_4 U car_5,"['parking_lot_4', 'car_5']",Stay in parking_lot_4 until you reach car_5,"{'parking lot 4': 'parking_lot_4', 'car 5': 'c...","{'parking_lot_4': 'ap_0', 'car_5': 'ap_1'}",ap_0 U ap_1,ConformalNL2LTL,prop U prop,prop U prop
...,...,...,...,...,...,...,...,...,...,...,...
252872,"if when possible withhold apple , whenever ven...","F ( ""withhold(apple)"" ) -> F ( ""venture_to(hou...","F""withhold(apple)"" -> F""venture_to(house)""","['""venture_to(house)""', '""withhold(apple)""']",NaN,NaN,NaN,Fap_1 -> Fap_0,VLTL-Bench_Prev,Fprop -> Fprop,Fprop -> Fprop
252873,always touch flag until gather orange,"G ( ""touch(flag)"" ) U ""gather(orange)""","G""touch(flag)"" U ""gather(orange)""","['""gather(orange)""', '""touch(flag)""']",NaN,NaN,NaN,Gap_1 U ap_0,VLTL-Bench_Prev,Gprop U prop,Gprop U prop
252874,at some time go_past flag or at some time make...,"F ( ""go_past(flag)"" ) | F ( ""make_your_way(fla...","F""go_past(flag)"" | F""make_your_way(flag)""","['""make_your_way(flag)""', '""go_past(flag)""']",NaN,NaN,NaN,Fap_1 | Fap_0,VLTL-Bench_Prev,Fprop | Fprop,Fprop | Fprop
252875,when possible proceed_to tree and at any time ...,"F ( ""proceed_to(tree)"" ) & F ( ""grab(pear)"" )","F""proceed_to(tree)"" & F""grab(pear)""","['""proceed_to(tree)""', '""grab(pear)""']",NaN,NaN,NaN,Fap_0 & Fap_1,VLTL-Bench_Prev,Fprop & Fprop,Fprop & Fprop
252876,whenever collect orange or at any time pass_by...,"F ( ""collect(orange)"" ) | F ( ""pass_by(house)"" )","F""collect(orange)"" | F""pass_by(house)""","['""pass_by(house)""', '""collect(orange)""']",NaN,NaN,NaN,Fap_1 | Fap_0,VLTL-Bench_Prev,Fprop | Fprop,Fprop | Fprop

In [136]:


import pandas as pd
import numpy as np



combined_df.groupby(['source', 'normalized_LTL_formula']).size().reset_index(name='count')

,source,normalized_LTL_formula,count
0,ConformalNL2LTL,!prop U (prop & F(prop & F(prop & prop))),10
1,ConformalNL2LTL,!prop U (prop & prop),7
2,ConformalNL2LTL,!prop U prop,40
3,ConformalNL2LTL,(!prop U prop) & F(prop & F(prop & F(prop & pr...,30
4,ConformalNL2LTL,(!prop U prop) & F(prop & Gprop),5
...,...,...,...
933,lifted_data_pureLTL.jsonl,prop | prop | G!prop,2
934,lifted_data_pureLTL.jsonl,prop | prop | G(prop U prop),2
935,lifted_data_pureLTL.jsonl,prop | prop | Gprop,29
936,lifted_data_pureLTL.jsonl,prop | prop | prop,4
937,lifted_data_pureLTL.jsonl,prop | prop | prop | prop,18

In [146]:
PATTERN_QUOTES = re.compile(
    r'(?:'
    r'"([^"\(\)]+)\(([^"\(\)]+)\)"?'   # left quote exists
    r'|'
    r'([^"\(\)]+)\(([^"\(\)]+)\)"'     # right quote exists
    r')'
)

# Regex:
# In column 2 only:
# Add a space after G/F/U/X if followed by lowercase letter
#
PATTERN_SPACING = re.compile(r'([GFUX])([a-z])')


# Regex:
# Replace hyphen with underscore
# EXCEPT when hyphen is part of ->
#
# Matches "-" not preceded by "-" and not followed by ">"
#
PATTERN_HYPHEN = re.compile(r'-(?!>)')


def transform_quotes(value: str) -> str:
    """
    Replace:

        "text1(text2)"
        "text1(text2
        text1(text2)"
        "text1(text2,text3)"

    with:

        text1_text2
        text1_text2_text3

    BUT do not touch:

        text1(text2)
    """

    def replacer(match):

        # Depending on which side had the quote,
        # one pair of groups will be None
        text1 = match.group(1) or match.group(3)
        inner = match.group(2) or match.group(4)

        text1 = text1.strip()
        inner = inner.strip()

        # Split comma-separated items
        parts = [p.strip() for p in inner.split(",")]

        # Join using underscores
        return "_".join([text1] + parts)

    return PATTERN_QUOTES.sub(replacer, value)


def add_spacing(value: str) -> str:
    """
    Add space after G/F/U/X when followed by lowercase letter.
    """

    return PATTERN_SPACING.sub(r'\1 \2', value)


def replace_hyphens(value: str) -> str:
    """
    Replace hyphens with underscores,
    except when part of the implies symbol '->'
    """

    return PATTERN_HYPHEN.sub("_", value)

combined_df['Spot LTL'] = combined_df['Spot LTL'].apply(transform_quotes).apply(add_spacing).apply(replace_hyphens)
combined_df['APs'] = combined_df['APs'].apply(transform_quotes).apply(add_spacing).apply(replace_hyphens)

In [147]:

def make_balanced_batches(
    df,
    type_col="normalized_LTL_formula",
    source_col="source",
    n_batches=9,
    per_batch=8,
    random_state=42,
):
    rng = np.random.default_rng(random_state)

    batches = {i: [] for i in range(n_batches)}
    batch_sizes = np.zeros(n_batches, dtype=int)

    grouped = list(df.groupby([type_col, source_col]))
    rng.shuffle(grouped)

    for pair, group in grouped:

        idx = group.index.to_numpy().copy()
        rng.shuffle(idx)

        total_needed = n_batches * per_batch

        # --------------------------------------------------------------
        # enough rows -> exactly 10 per batch
        # --------------------------------------------------------------
        if len(idx) >= total_needed:

            selected = idx[:total_needed]

            for b in range(n_batches):
                rows = selected[b * per_batch:(b + 1) * per_batch]

                batches[b].extend(rows)
                batch_sizes[b] += len(rows)

        # --------------------------------------------------------------
        # fewer than 90 rows
        # distribute evenly with max difference = 1
        # --------------------------------------------------------------
        else:

            k = len(idx)

            base = k // n_batches
            remainder = k % n_batches

            # give extra rows to currently smallest batches
            ordered_batches = list(np.argsort(batch_sizes))

            counts = [base] * n_batches

            for i in range(remainder):
                counts[ordered_batches[i]] += 1

            ptr = 0

            for b in range(n_batches):

                take = counts[b]

                if take > 0:
                    rows = idx[ptr:ptr + take]

                    batches[b].extend(rows)
                    batch_sizes[b] += len(rows)

                    ptr += take

    batch_dfs = []

    for b in range(n_batches):

        batch_df = (
            df.loc[batches[b]]
            .sample(frac=1, random_state=random_state)
            .reset_index(drop=True)
        )

        batch_df["batch_id"] = b

        batch_dfs.append(batch_df)

    return batch_dfs

thisisit = make_balanced_batches(combined_df)


# Stack them vertically
thisisit = pd.concat(thisisit, ignore_index=True)
thisisit.sort_values(by=['batch_id']).reset_index(drop=True)

,original NL,original LTL,Spot LTL,APs,ap_NL,dict_AP,AP_lifted_dict,lifted_LTL,source,normalized_LTL_formula,lifted_lifted_LTL_formula,batch_id
0,"If get_help ever holds, avoid the impending_ga...","( F ""get_help"" ) -> ( ! ""get_help"" U ( ""avoid(...",F get_help -> (!get_help U (avoid_impending_ga...,"['get_help', 'avoid_impending_gas_leak']",NaN,NaN,NaN,Fap_0 -> (!ap_0 U (ap_1 & !ap_0)),VLTL-Bench_New,Fprop -> (!prop U (prop & !prop)),Fprop -> (!prop U (prop & !prop)),0
1,Make sure that (prop_2) is equivalent to (prop...,( ( prop_2 <-> prop_1 ) & G prop_3 ),(prop_1 <-> prop_2) & G prop_3,"['prop_1', 'prop_2', 'prop_3']",NaN,NaN,NaN,(ap_0 <-> ap_1) & Gap_2,lifted_data_pureLTL.jsonl,(prop <-> prop) & Gprop,(prop <-> prop) & Gprop,0
2,"Whenever change light_west green holds, photo ...","G ( ""change(light_west,green)"" -> X ( X ( X ""p...",G(change_light_west_green -> XXX photo_vehicle...,"['change_light_west_green', 'photo_vehicle_nor...",NaN,NaN,NaN,G(ap_0 -> XXXap_1),VLTL-Bench_New,G(prop -> XXXprop),G(prop -> XXXprop),0
3,( prop_1 ) or at any time ( prop_2 ),( prop_1 | F prop_2 ),prop_1 | F prop_2,"['prop_1', 'prop_2']",NaN,NaN,NaN,ap_0 | Fap_1,lifted_data_pureLTL.jsonl,prop | Fprop,prop | Fprop,0
4,"If (prop_4) is equivalent to (prop_2), then ke...",( ( prop_4 <-> prop_2 ) -> ( prop_1 U prop_3 ) ),(prop_2 <-> prop_4) -> (prop_1 U prop_3),"['prop_1', 'prop_2', 'prop_3', 'prop_4']",NaN,NaN,NaN,(ap_1 <-> ap_3) -> (ap_0 U ap_2),lifted_data_pureLTL.jsonl,(prop <-> prop) -> (prop U prop),(prop <-> prop) -> (prop U prop),0
...,...,...,...,...,...,...,...,...,...,...,...,...
17966,Stay out of garage 1 until you take a picture ...,!garage_1 U photo&&<>(landmark_5&&photo),(!garage_1 U photo) & F(landmark_5 & photo),"['photo', 'garage_1', 'landmark_5']",Stay out of garage_1 until you take a picture ...,"{'photo': 'photo', 'garage 1': 'garage_1', 'la...","{'photo': 'ap_0', 'garage_1': 'ap_1', 'landmar...",(!ap_1 U ap_0) & F(ap_2 & ap_0),ConformalNL2LTL,(!prop U prop) & F(prop & prop),(!prop U prop) & F(prop & prop),8
17967,Call for help holds at all times.,"G ""get_help""",G get_help,['get_help'],NaN,NaN,NaN,Gap_0,VLTL-Bench_New,Gprop,Gprop,8
17968,It is required that eventually (prop_1) should...,( ( F prop_1 <-> prop_2 ) & ! prop_3 ),!prop_3 & (prop_2 <-> F prop_1),"['prop_1', 'prop_2', 'prop_3']",NaN,NaN,NaN,!ap_2 & (ap_1 <-> Fap_0),lifted_data_pureLTL.jsonl,!prop & (prop <-> Fprop),!prop & (prop <-> Fprop),8
17969,Go to hospital_3 and pickup water bottle_4 whi...,"F ( ""hospital_3"" & ""p_bottle_4"" ) & G ! ""pharm...",F(hospital_3 & p_bottle_4) & G!pharmacy_2,"['p_bottle_4', 'hospital_3', 'pharmacy_2']",NaN,NaN,NaN,F(ap_1 & ap_0) & G!ap_2,VLTL-Bench_Prev,F(prop & prop) & G!prop,F(prop & prop) & G!prop,8
17970,"Either (prop_1) does not happen, or both (prop...",( ! prop_1 | ( prop_3 & prop_2 ) ),!prop_1 | (prop_2 & prop_3),"['prop_1', 'prop_2', 'prop_3']",NaN,NaN,NaN,!ap_0 | (ap_1 & ap_2),lifted_data_pureLTL.jsonl,!prop | (prop & prop),!prop | (prop & prop),8

In [148]:
final_df = thisisit

# 2. Turn that label into an actual column called 'sample_number'

# 3. Fix the row index so it is clean (0, 1, 2...)
final_df = final_df.reset_index(drop=True)

final_df.to_csv('Batch9/final_df.csv', index=False, sep=';')

In [149]:
dist_df_final = final_df.groupby(['batch_id', 'source', 'normalized_LTL_formula']).size().reset_index(name='size')
dist_df_final

,batch_id,source,normalized_LTL_formula,size
0,0,ConformalNL2LTL,!prop U (prop & F(prop & F(prop & prop))),2
1,0,ConformalNL2LTL,!prop U (prop & prop),1
2,0,ConformalNL2LTL,!prop U prop,4
3,0,ConformalNL2LTL,(!prop U prop) & F(prop & F(prop & F(prop & pr...,3
4,0,ConformalNL2LTL,(!prop U prop) & F(prop & prop),3
...,...,...,...,...
5728,8,lifted_data_pureLTL.jsonl,prop | prop | Fprop,3
5729,8,lifted_data_pureLTL.jsonl,prop | prop | G(prop U prop),1
5730,8,lifted_data_pureLTL.jsonl,prop | prop | Gprop,3
5731,8,lifted_data_pureLTL.jsonl,prop | prop | prop,1
5732,8,lifted_data_pureLTL.jsonl,prop | prop | prop | prop,2

In [150]:
counts_df = dist_df_final.groupby(['source', 'normalized_LTL_formula', 'batch_id'])['size'].sum().reset_index(name='count')
counts_df.to_csv('dist/counts_df.csv', index=False)

In [151]:
counts_df.groupby(['batch_id'])['count'].sum().reset_index(name='total_count')

   batch_id  total_count
0         0         1997
1         1         1997
2         2         1997
3         3         1997
4         4         1997
5         5         1996
6         6         1997
7         7         1997
8         8         1996

In [145]:
import pickle

# Save the remaining pool
with open('full_nested_dict.pkl', 'wb') as f:
    pickle.dump(nested_dict, f)

In [16]:
import random
def sample_and_remove(data_dict, sample_size=10):
    samples = {}
    
    for source, formulas in data_dict.items():
        samples[source] = {}
        for formula, pairs_set in formulas.items():
            # Convert set to list to allow sampling
            pairs_list = list(pairs_set)
            
            # Determine how many we can actually take
            actual_sample_size = min(len(pairs_list), sample_size)
            
            # Randomly select items
            selected = random.sample(pairs_list, actual_sample_size)
            
            # Store them in our result
            samples[source][formula] = selected
            
            # Remove the selected items from the original dictionary
            # This ensures they won't be picked in the next "later time" call
            for item in selected:
                pairs_set.remove(item)
                
    return samples
first_batch = sample_and_remove(nested_dict, sample_size=12)

In [17]:
first_batch

{'ConformalNL2LTL': {'!prop U (prop & F(prop & F(prop & prop)))': [('Do not go to room 2 before retrieving bottle 4 from kitchen 1 and putting it on table 4',
    '!room_2 U (kitchen_1 & F(p_bottle_4 & F(pd & table_4)))',
    "['pd', 'table_4', 'room_2', 'kitchen_1', 'p_bottle_4']",
    '!prop U (prop & F(prop & F(prop & prop)))',
    'ConformalNL2LTL'),
   ('Do not go to locality 5 before collecting pass 5 from house 2 and delivering it to office 3',
    '!locality_5 U (house_2 & F(p_pass_5 & F(office_3 & pd)))',
    "['pd', 'office_3', 'house_2', 'locality_5', 'p_pass_5']",
    '!prop U (prop & F(prop & F(prop & prop)))',
    'ConformalNL2LTL'),
   ('Stay out of locality 5 until you retrieve pass 5 from house 2 and put it in office 3',
    '!locality_5 U (house_2 & F(p_pass_5 & F(office_3 & pd)))',
    "['pd', 'office_3', 'house_2', 'locality_5', 'p_pass_5']",
    '!prop U (prop & F(prop & F(prop & prop)))',
    'ConformalNL2LTL'),
   ('Do not enter locality 5 until you pick up pass 5 from house 2 and put it in office 3',
    '!locality_5 U (house_2 & F(p_pass_5 & F(office_3 & pd)))',
    "['pd', 'office_3', 'house_2', 'locality_5', 'p_pass_5']",
    '!prop U (prop & F(prop & F(prop & prop)))',
    'ConformalNL2LTL'),
   ('Avoid entering room 2 until you take bottle 4 from kitchen 1 and place it on table 4',
    '!room_2 U (kitchen_1 & F(p_bottle_4 & F(pd & table_4)))',
    "['pd', 'table_4', 'room_2', 'kitchen_1', 'p_bottle_4']",
    '!prop U (prop & F(prop & F(prop & prop)))',
    'ConformalNL2LTL'),
   ('Avoid entering locality 5 until you pick up pass 5 from house 2 and place it in office 3',
    '!locality_5 U (house_2 & F(p_pass_5 & F(office_3 & pd)))',
    "['pd', 'office_3', 'house_2', 'locality_5', 'p_pass_5']",
    '!prop U (prop & F(prop & F(prop & prop)))',
    'ConformalNL2LTL'),
   ('Do not go to room 2 until you take bottle 4 from kitchen 1, and then put it on table 4',
    '!room_2 U (kitchen_1 & F(p_bottle_4 & F(pd & table_4)))',
    "['pd', 'table_4', 'room_2', 'kitchen_1', 'p_bottle_4']",
    '!prop U (prop & F(prop & F(prop & prop)))',
    'ConformalNL2LTL'),
   ('Refrain from entering locality 5 until you collect pass 5 from house 2 and deposit it in office 3',
    '!locality_5 U (house_2 & F(p_pass_5 & F(office_3 & pd)))',
    "['pd', 'office_3', 'house_2', 'locality_5', 'p_pass_5']",
    '!prop U (prop & F(prop & F(prop & prop)))',
    'ConformalNL2LTL'),
   ('Refrain from going to room 2 until you pick up bottle 4 from kitchen 1 and place it on table 4',
    '!room_2 U (kitchen_1 & F(p_bottle_4 & F(pd & table_4)))',
    "['pd', 'table_4', 'room_2', 'kitchen_1', 'p_bottle_4']",
    '!prop U (prop & F(prop & F(prop & prop)))',
    'ConformalNL2LTL'),
   ('Stay away from room 2 until you collect bottle 4 from kitchen 1 and deliver it to table 4',
    '!room_2 U (kitchen_1 & F(p_bottle_4 & F(pd & table_4)))',
    "['pd', 'table_4', 'room_2', 'kitchen_1', 'p_bottle_4']",
    '!prop U (prop & F(prop & F(prop & prop)))',
    'ConformalNL2LTL')],
  '!prop U (prop & prop)': [('Refrain from entering park 9 until you reach gate 7 and take a picture there',
    '!park_9 U (gate_7 & photo)',
    "['photo', 'park_9', 'gate_7']",
    '!prop U (prop & prop)',
    'ConformalNL2LTL'),
   ('Avoid entering park 9 until you visit gate 7 and take a picture',
    '!park_9 U (gate_7 & photo)',
    "['photo', 'park_9', 'gate_7']",
    '!prop U (prop & prop)',
    'ConformalNL2LTL'),
   ('Do not enter park 9 until you go to gate 7 and take a picture',
    '!park_9 U (gate_7 & photo)',
    "['photo', 'park_9', 'gate_7']",
    '!prop U (prop & prop)',
    'ConformalNL2LTL'),
   ('Stay away from park 9 until you go to gate 7 and ensure you take a photograph',
    '!park_9 U (gate_7 & photo)',
    "['photo', 'park_9', 'gate_7']",
    '!prop U (prop & prop)',
    'ConformalNL2LTL'),
   ('Do not enter garage 1 until you take a picture of landmark 5',
    '!garage_1 U (landmark_5 & photo)',
    "['photo', 'garage_1', 'landmark_5']",
    '!prop U (prop & prop)',
    'ConformalNL2LTL'),
   ('Do not go to park 9 before arriving at gate 7 and capturing a photo',
    '!park_9 U (gate_7 & photo)',
    "['photo', 'park_9', 'gate_7']",
    '!prop U (prop & prop)',
    'ConformalNL2LTL'),
   ('Do not go to street 5 before reaching store 1 and taking package 4 from there.',
    '!street_5 U (p_package_4 & store_1)',
    "['p_package_4', 'street_5', 'store_1']",
    '!prop U (prop & prop)',
    'ConformalNL2LTL')],
  '!prop U prop': [('Avoid going to building 8 until you have reached parking lot 8',
    '!building_8 U parking_lot_8',
    "['building_8', 'parking_lot_8']",
    '!prop U prop',
    'ConformalNL2LTL'),
   ('Stay away from park 6 until you collect pass 4',
    '!park_6 U p_pass_4',
    "['park_6', 'p_pass_4']",
    '!prop U prop',
    'ConformalNL2LTL'),
   ('Ensure you stay away from building 8 until parking lot 8 is visited',
    '!building_8 U parking_lot_8',
    "['building_8', 'parking_lot_8']",
    '!prop U prop',
    'ConformalNL2LTL'),
   ('Do not enter park 6 unless you have already picked up pass 4',
    '!park_6 U p_pass_4',
    "['park_6', 'p_pass_4']",
    '!prop U prop',
    'ConformalNL2LTL'),
   ('Refrain from entering building 8 unless you have already reached parking lot 8',
    '!building_8 U parking_lot_8',
    "['building_8', 'parking_lot_8']",
    '!prop U prop',
    'ConformalNL2LTL'),
   ('Do not enter building 8 until you reach parking lot 8',
    '!building_8 U parking_lot_8',
    "['building_8', 'parking_lot_8']",
    '!prop U prop',
    'ConformalNL2LTL'),
   ('Stay away from parking lot 4 until building 8 is reached',
    '!parking_lot_4 U building_8',
    "['building_8', 'parking_lot_4']",
    '!prop U prop',
    'ConformalNL2LTL'),
   ('Do not pick up cone 2 until you go to intersection 4',
    '!p_cone_2 U intersection_4',
    "['intersection_4', 'p_cone_2']",
    '!prop U prop',
    'ConformalNL2LTL'),
   ('Stay away from intersection 4 until you get to street 5',
    '!intersection_4 U street_5',
    "['street_5', 'intersection_4']",
    '!prop U prop',
    'ConformalNL2LTL'),
   ('Avoid entering building 1 until street 4 has been reached.',
    '!building_1 U street_4',
    "['building_1', 'street_4']",
    '!prop U prop',
    'ConformalNL2LTL'),
   ('Avoid entering park 5 until you have reached intersection 4',
    '!park_5 U intersection_4',
    "['park_5', 'intersection_4']",
    '!prop U prop',
    'ConformalNL2LTL'),
   ('Ensure building 1 is avoided until reaching street 4.',
    '!building_1 U street_4',
    "['building_1', 'street_4']",
    '!prop U prop',
    'ConformalNL2LTL')],
  '(!prop U prop) & F(prop & F(prop & F(prop & prop)))': [('Do not enter building 3 before arriving at street 6, while ensuring you take box 8 from store 3 to house 2',
    '(!building_3 U street_6) & F(store_3 & F(p_box_8 & F(house_2 & pd)))',
    "['pd', 'street_6', 'house_2', 'building_3', 'store_3', 'p_box_8']",
    '(!prop U prop) & F(prop & F(prop & F(prop & prop)))',
    'ConformalNL2LTL'),
   ('Ensure you stay away from intersection 5 until street 4 is reached, while delivering pass 4 from house 4 to office 1',
    '(!intersection_5 U street_4) & F(house_4 & F(p_pass_4 & F(office_1 & pd)))',
    "['pd', 'street_4', 'house_4', 'intersection_5', 'p_pass_4', 'office_1']",
    '(!prop U prop) & F(prop & F(prop & F(prop & prop)))',
    'ConformalNL2LTL'),
   ('Do not go to office 4 until you pick pass 6 as you deliver pass 6 from house 5 to office 4',
    '(!office_4 U p_pass_6) & F(house_5 & F(p_pass_6 & F(office_4 & pd)))',
    "['pd', 'office_4', 'house_5', 'p_pass_6']",
    '(!prop U prop) & F(prop & F(prop & F(prop & prop)))',
    'ConformalNL2LTL'),
   ('Refrain from entering intersection 1 until you reach street 6, and then move cone 3 from street 2 to intersection 1',
    '(!intersection_1 U street_6) & F(street_2 & F(p_cone_3 & F(intersection_1 & pd)))',
    "['pd', 'street_6', 'street_2', 'intersection_1', 'p_cone_3']",
    '(!prop U prop) & F(prop & F(prop & F(prop & prop)))',
    'ConformalNL2LTL'),
   ('Do not enter intersection 1 until you reach street 6 as you take cone 3 from street 2 and put it in intersection 1',
    '(!intersection_1 U street_6) & F(street_2 & F(p_cone_3 & F(intersection_1 & pd)))',
    "['pd', 'street_6', 'street_2', 'intersection_1', 'p_cone_3']",
    '(!prop U prop) & F(prop & F(prop & F(prop & prop)))',
    'ConformalNL2LTL'),
   ('Do not approach building 3 until you reach street 6 as you bring box 8 from store 3 to house 2',
    '(!building_3 U street_6) & F(store_3 & F(p_box_8 & F(house_2 & pd)))',
    "['pd', 'street_6', 'house_2', 'building_3', 'store_3', 'p_box_8']",
    '(!prop U prop) & F(prop & F(prop & F(prop & prop)))',
    'ConformalNL2LTL'),
   ('Avoid going to building 3 until you reach street 6, and then transport box 8 from store 3 to house 2',
    '(!building_3 U street_6) & F(store_3 & F(p_box_8 & F(house_2 & pd)))',
    "['pd', 'street_6', 'house_2', 'building_3', 'store_3', 'p_box_8']",
    '(!prop U prop) & F(prop & F(prop & F(prop & prop)))',
    'ConformalNL2LTL'),
   ('Avoid office 4 until pick up pass 6, then you need to pick it up at house 5 and deliver it to office 4',
    '(!office_4 U p_pass_6) & F(house_5 & F(p_pass_6 & F(office_4 & pd)))',
    "['pd', 'office_4', 'house_5', 'p_pass_6']",
    '(!prop U prop) & F(prop & F(prop & F(prop & prop)))',
    'ConformalNL2LTL'),
   ('Refrain from entering store 4 until you arrive at street 6, while delivering package 8 from office 2 to store 4',
    '(!store_4 U street_6) & F(office_2 & F(p_package_8 & F(pd & store_4)))',
    "['pd', 'street_6', 'p_package_8', 'store_4', 'office_2']",
    '(!prop U prop) & F(prop & F(prop & F(prop & prop)))',
    'ConformalNL2LTL'),
   ('Do not go to building 3 until you reach street 6 as you take box 8 from store 3 to house 2',
    '(!building_3 U street_6) & F(store_3 & F(p_box_8 & F(house_2 & pd)))',
    "['pd', 'street_6', 'house_2', 'building_3', 'store_3', 'p_box_8']",
    '(!prop U prop) & F(prop & F(prop & F(prop & prop)))',
    'ConformalNL2LTL'),
   ('Stay away from intersection 1 until you get to street 6, and afterward, deliver cone 3 from street 2 to intersection 1',
    '(!intersection_1 U street_6) & F(street_2 & F(p_cone_3 & F(intersection_1 & pd)))',
    "['pd', 'street_6', 'street_2', 'intersection_1', 'p_cone_3']",
    '(!prop U prop) & F(prop & F(prop & F(prop & prop)))',
    'ConformalNL2LTL'),
   ('Refrain from entering park 4 until you arrive at street 3, and then take takeout 2 from store 7 to bench 3',
    '(!park_4 U street_3) & F(store_7 & F(p_takeout_2 & F(bench_3 & pd)))',
    "['pd', 'street_3', 'park_4', 'store_7', 'p_takeout_2', 'bench_3']",
    '(!prop U prop) & F(prop & F(prop & F(prop & prop)))',
    'ConformalNL2LTL')],
  '(!prop U prop) & F(prop & Gprop)': [('Do not visit parking lot 4 before reaching street 5, and after that, proceed to enter and remain there',
    '(!parking_lot_4 U street_5) & F(parking_lot_4 & Gparking_lot_4)',
    "['street_5', 'parking_lot_4']",
    '(!prop U prop) & F(prop & Gprop)',
    'ConformalNL2LTL'),
   ('Refrain from going to parking lot 4 until you arrive at street 5, and then ensure you enter and stay in parking lot 4',
    '(!parking_lot_4 U street_5) & F(parking_lot_4 & Gparking_lot_4)',
    "['street_5', 'parking_lot_4']",
    '(!prop U prop) & F(prop & Gprop)',
    'ConformalNL2LTL'),
   ('Do not enter parking lot 4 until you reach street 5 as you enter and stay in parking lot 4',
    '(!parking_lot_4 U street_5) & F(parking_lot_4 & Gparking_lot_4)',
    "['street_5', 'parking_lot_4']",
    '(!prop U prop) & F(prop & Gprop)',
    'ConformalNL2LTL'),
   ('Stay away from parking lot 4 until you reach street 5, after which you must enter and stay in parking lot 4 continuously',
    '(!parking_lot_4 U street_5) & F(parking_lot_4 & Gparking_lot_4)',
    "['street_5', 'parking_lot_4']",
    '(!prop U prop) & F(prop & Gprop)',
    'ConformalNL2LTL'),
   ('Avoid entering parking lot 4 until you reach street 5 and then enter and remain in parking lot 4',
    '(!parking_lot_4 U street_5) & F(parking_lot_4 & Gparking_lot_4)',
    "['street_5', 'parking_lot_4']",
    '(!prop U prop) & F(prop & Gprop)',
    'ConformalNL2LTL')],
  '(!prop U prop) & F(prop & prop)': [('Avoid entering street 4 until you reach intersection 2 while going to house 13 to pick up trash 13',
    '(!street_4 U intersection_2) & F(house_13 & p_trash_13)',
    "['street_4', 'intersection_2', 'house_13', 'p_trash_13']",
    '(!prop U prop) & F(prop & prop)',
    'ConformalNL2LTL'),
   ('Refrain from entering landmark 5 until you reach park 5, and then ensure you take a picture of landmark 5 at some point',
    '(!landmark_5 U park_5) & F(landmark_5 & photo)',
    "['photo', 'park_5', 'landmark_5']",
    '(!prop U prop) & F(prop & prop)',
    'ConformalNL2LTL'),
   ('Do not go to landmark 5 before reaching park 5, and ensure you eventually take a picture of landmark 5',
    '(!landmark_5 U park_5) & F(landmark_5 & photo)',
    "['photo', 'park_5', 'landmark_5']",
    '(!prop U prop) & F(prop & prop)',
    'ConformalNL2LTL'),
   ('Ensure you avoid street 4 until intersection 2 is reached while picking up trash 13 at house 13',
    '(!street_4 U intersection_2) & F(house_13 & p_trash_13)',
    "['street_4', 'intersection_2', 'house_13', 'p_trash_13']",
    '(!prop U prop) & F(prop & prop)',
    'ConformalNL2LTL'),
   ('Do not go to street 4 before reaching intersection 2, as you proceed to house 13 and collect trash 13',
    '(!street_4 U intersection_2) & F(house_13 & p_trash_13)',
    "['street_4', 'intersection_2', 'house_13', 'p_trash_13']",
    '(!prop U prop) & F(prop & prop)',
    'ConformalNL2LTL'),
   ('Stay out of garage 1 until you take a picture as part of photographing landmark 5',
    '(!garage_1 U photo) & F(landmark_5 & photo)',
    "['photo', 'garage_1', 'landmark_5']",
    '(!prop U prop) & F(prop & prop)',
    'ConformalNL2LTL'),
   ('Avoid entering street 5 until you reach store 1, and ensure that you eventually go to store 1 and pick up package 4',
    '(!street_5 U store_1) & F(p_package_4 & store_1)',
    "['p_package_4', 'street_5', 'store_1']",
    '(!prop U prop) & F(prop & prop)',
    'ConformalNL2LTL'),
   ('Do not take any pictures before reaching park 5, and ensure you eventually take a picture of landmark 4',
    '(!photo U park_5) & F(landmark_4 & photo)',
    "['photo', 'park_5', 'landmark_4']",
    '(!prop U prop) & F(prop & prop)',
    'ConformalNL2LTL'),
   ('Avoid landmark 5 until you reach park 5, and eventually take a picture of landmark 5.',
    '(!landmark_5 U park_5) & F(landmark_5 & photo)',
    "['photo', 'park_5', 'landmark_5']",
    '(!prop U prop) & F(prop & prop)',
    'ConformalNL2LTL'),
   ('Avoid taking a photo until you reach park 5, and ensure that you eventually go to landmark 4 and take a picture there',
    '(!photo U park_5) & F(landmark_4 & photo)',
    "['photo', 'park_5', 'landmark_4']",
    '(!prop U prop) & F(prop & prop)',
    'ConformalNL2LTL'),
   ('Avoid garage 1 until you have taken a picture alongside taking a picture of landmark 5',
    '(!garage_1 U photo) & F(landmark_5 & photo)',
    "['photo', 'garage_1', 'landmark_5']",
    '(!prop U prop) & F(prop & prop)',
    'ConformalNL2LTL'),
   ('Ensure you stay away from street 5 until you get to store 1 to deliver package 4',
    '(!street_5 U store_1) & F(p_package_4 & store_1)',
    "['p_package_4', 'street_5', 'store_1']",
    '(!prop U prop) & F(prop & prop)',
    'ConformalNL2LTL')],
  '(!prop U prop) & FGprop': [('Stay away from street 4 until you arrive at intersection 6 and then proceed to and remain in street 4',
    '(!street_4 U intersection_6) & FGstreet_4',
    "['street_4', 'intersection_6']",
    '(!prop U prop) & FGprop',
    'ConformalNL2LTL'),
   ('Avoid going to street 4 until you reach intersection 6, after which you must go to and remain in street 4',
    '(!street_4 U intersection_6) & FGstreet_4',
    "['street_4', 'intersection_6']",
    '(!prop U prop) & FGprop',
    'ConformalNL2LTL'),
   ('Do not enter street 4 before reaching intersection 6 and then stay in street 4 continuously',
    '(!street_4 U intersection_6) & FGstreet_4',
    "['street_4', 'intersection_6']",
    '(!prop U prop) & FGprop',
    'ConformalNL2LTL'),
   ('Do not go to street 4 until you reach intersection 6 as you go to and stay in street 4',
    '(!street_4 U intersection_6) & FGstreet_4',
    "['street_4', 'intersection_6']",
    '(!prop U prop) & FGprop',
    'ConformalNL2LTL'),
   ('Do not enter building 3 until you arrive at garage 3, and once there, remain in building 3',
    '(!building_3 U garage_3) & FGbuilding_3',
    "['building_3', 'garage_3']",
    '(!prop U prop) & FGprop',
    'ConformalNL2LTL'),
   ('Refrain from visiting street 4 until you have reached intersection 6, after which you must transition to and stay in street 4',
    '(!street_4 U intersection_6) & FGstreet_4',
    "['street_4', 'intersection_6']",
    '(!prop U prop) & FGprop',
    'ConformalNL2LTL')],
  '(!prop U prop) & Fprop': [('Avoid going to intersection 8 until you reach street 3, and then proceed to locality 5',
    '(!intersection_8 U street_3) & Flocality_5',
    "['intersection_8', 'street_3', 'locality_5']",
    '(!prop U prop) & Fprop',
    'ConformalNL2LTL'),
   ('Do not go to intersection 8 until you reach street 3 as you go to locality 5',
    '(!intersection_8 U street_3) & Flocality_5',
    "['intersection_8', 'street_3', 'locality_5']",
    '(!prop U prop) & Fprop',
    'ConformalNL2LTL'),
   ('Do not enter intersection 8 before arriving at street 3, while ensuring you eventually go to locality 5',
    '(!intersection_8 U street_3) & Flocality_5',
    "['intersection_8', 'street_3', 'locality_5']",
    '(!prop U prop) & Fprop',
    'ConformalNL2LTL'),
   ('Stay away from intersection 8 until street 3 is reached, and ensure you go to locality 5 afterward',
    '(!intersection_8 U street_3) & Flocality_5',
    "['intersection_8', 'street_3', 'locality_5']",
    '(!prop U prop) & Fprop',
    'ConformalNL2LTL'),
   ('Refrain from visiting intersection 8 until you reach street 3 and then make your way to locality 5',
    '(!intersection_8 U street_3) & Flocality_5',
    "['intersection_8', 'street_3', 'locality_5']",
    '(!prop U prop) & Fprop',
    'ConformalNL2LTL')],
  '(prop U prop) & F(prop & F(prop & F(prop & prop)))': [('Remain in locality 1 until you arrive intersection 4 as you take package 5 from warehouse 9 to store 2',
    '(locality_1 U intersection_4) & F(warehouse_9 & F(p_package_5 & F(pd & store_2)))',
    "['pd', 'p_package_5', 'store_2', 'intersection_4', 'locality_1', 'warehouse_9']",
    '(prop U prop) & F(prop & F(prop & F(prop & prop)))',
    'ConformalNL2LTL'),
   ('Stay in locality 1 until you reach intersection 4 as you take package 5 from warehouse 9 to store 2',
    '(locality_1 U intersection_4) & F(warehouse_9 & F(p_package_5 & F(pd & store_2)))',
    "['pd', 'p_package_5', 'store_2', 'intersection_4', 'locality_1', 'warehouse_9']",
    '(prop U prop) & F(prop & F(prop & F(prop & prop)))',
    'ConformalNL2LTL'),
   ('Stay in park 5 until you reach bench 4, and ensure you eventually go to store 2 and pick up bottle 5 and deliver it to bench 4',
    '(park_5 U bench_4) & F(store_2 & F(p_bottle_5 & F(bench_4 & pd)))',
    "['pd', 'park_5', 'store_2', 'bench_4', 'p_bottle_5']",
    '(prop U prop) & F(prop & F(prop & F(prop & prop)))',
    'ConformalNL2LTL'),
   ('Stay in park 5 until you reach bench 4 and ensure you eventually go to store 2 and  pick up bottle 5 and deliver it to bench 4',
    '(park_5 U bench_4) & F(store_2 & F(p_bottle_5 & F(bench_4 & pd)))',
    "['pd', 'park_5', 'store_2', 'bench_4', 'p_bottle_5']",
    '(prop U prop) & F(prop & F(prop & F(prop & prop)))',
    'ConformalNL2LTL'),

In [18]:
with open('first_batch.pkl', 'wb') as f:
    pickle.dump(first_batch, f)

In [19]:
with open('remaining_pool.pkl', 'wb') as f:
    pickle.dump(nested_dict, f)

In [34]:
with open('remaining_pool.pkl', 'rb') as f:
    nested_dict = pickle.load(f)

In [35]:
second_batch = sample_and_remove(nested_dict, sample_size=10)

In [ ]:

with open('second_batch.pkl', 'wb') as f:
    pickle.dump(second_batch, f)

In [1]:
import pickle

with open('first_batch.pkl', 'rb') as f:
    first_batch = pickle.load(f)

In [28]:
aaa=0
for elem in first_batch:
    for formula in first_batch[elem]:
        print(elem, formula, len(set(first_batch[elem][formula])))
        aaa+=len(first_batch[elem][formula])

ConformalNL2LTL !prop U (prop & F(prop & F(prop & prop))) 10
ConformalNL2LTL !prop U (prop & prop) 7
ConformalNL2LTL !prop U prop 12
ConformalNL2LTL (!prop U prop) & F(prop & F(prop & F(prop & prop))) 12
ConformalNL2LTL (!prop U prop) & F(prop & Gprop) 5
ConformalNL2LTL (!prop U prop) & F(prop & prop) 12
ConformalNL2LTL (!prop U prop) & FGprop 6
ConformalNL2LTL (!prop U prop) & Fprop 5
ConformalNL2LTL (prop U prop) & F(prop & F(prop & F(prop & prop))) 10
ConformalNL2LTL F(prop & F(prop & F(prop & Gprop))) 12
ConformalNL2LTL F(prop & F(prop & F(prop & prop & prop))) 5
ConformalNL2LTL F(prop & F(prop & F(prop & prop))) 12
ConformalNL2LTL F(prop & F(prop & F(prop & prop))) & (!prop U prop) 5
ConformalNL2LTL F(prop & F(prop & F(prop & prop))) & F(prop & Gprop) 5
ConformalNL2LTL F(prop & F(prop & F(prop & prop))) & G!prop 11
ConformalNL2LTL F(prop & F(prop & Gprop)) 11
ConformalNL2LTL F(prop & F(prop & prop & Gprop)) 5
ConformalNL2LTL F(prop & F(prop & prop)) 12
ConformalNL2LTL F(prop & Fprop) 10
ConformalNL2LTL F(prop & prop & F(prop & Gprop)) 12
ConformalNL2LTL F(prop & prop & Gprop) 12
ConformalNL2LTL F(prop & prop) 12
ConformalNL2LTL F(prop & prop) & (!prop U prop) 9
ConformalNL2LTL F(prop & prop) & G!prop 12
ConformalNL2LTL F(prop & prop) & Gprop 5
ConformalNL2LTL FGprop 12
ConformalNL2LTL FGprop & (!prop U prop) 8
ConformalNL2LTL Fprop 5
ConformalNL2LTL Fprop & G!prop 12
ConformalNL2LTL G!(prop & prop) 10
ConformalNL2LTL G!(prop | prop) 10
ConformalNL2LTL G!prop 12
ConformalNL2LTL G!prop & F(prop & F(prop & F(prop & prop))) 10
ConformalNL2LTL G!prop & F(prop & prop & F(prop & prop)) 4
ConformalNL2LTL G!prop & F(prop & prop) 12
ConformalNL2LTL G!prop & Fprop 10
ConformalNL2LTL G!prop & GF(prop & prop) 5
ConformalNL2LTL GF(prop & F(prop & F(prop & prop))) 12
ConformalNL2LTL GF(prop & F(prop & F(prop & prop))) & GFprop 12
ConformalNL2LTL GF(prop & prop) 12
ConformalNL2LTL GF(prop & prop) & (!prop U prop) 5
ConformalNL2LTL GF(prop & prop) & G!prop 10
ConformalNL2LTL GF(prop & prop) & GF(prop & F(prop & F(prop & prop))) 5
ConformalNL2LTL GF(prop & prop) & GF(prop & prop) 5
ConformalNL2LTL GF(prop & prop) & GFprop 12
ConformalNL2LTL GFprop 12
ConformalNL2LTL GFprop & F(prop & F(prop & F(prop & prop))) 12
ConformalNL2LTL GFprop & Fprop 10
ConformalNL2LTL GFprop & GF(prop & F(prop & F(prop & prop))) 12
ConformalNL2LTL GFprop & GF(prop & prop) 12
ConformalNL2LTL Gprop 12
ConformalNL2LTL Gprop & F(prop & F(prop & F(prop & prop))) 12
ConformalNL2LTL Gprop & GF(prop & F(prop & F(prop & prop))) 5
ConformalNL2LTL Gprop & GF(prop & prop) 10
ConformalNL2LTL prop U (prop & F(prop & F(prop & prop))) 12
ConformalNL2LTL prop U (prop & prop & F(prop & Gprop)) 10
ConformalNL2LTL prop U (prop & prop) 12
ConformalNL2LTL prop U prop 12
NL-to-LTL-Synthetic-Datasetprocessed_data F(prop & prop & prop) 12
NL-to-LTL-Synthetic-Datasetprocessed_data F(prop & prop) 12
NL-to-LTL-Synthetic-Datasetprocessed_data F(prop | prop | prop) 12
NL-to-LTL-Synthetic-Datasetprocessed_data F(prop | prop) 12
NL-to-LTL-Synthetic-Datasetprocessed_data Fprop 5
NL-to-LTL-Synthetic-Datasetprocessed_data G!(prop & prop & prop) 12
NL-to-LTL-Synthetic-Datasetprocessed_data G!(prop & prop) 12
NL-to-LTL-Synthetic-Datasetprocessed_data G!(prop & prop) | F(prop & prop & F(prop & prop)) 12
NL-to-LTL-Synthetic-Datasetprocessed_data G!(prop & prop) | F(prop & prop & F(prop | prop)) 12
NL-to-LTL-Synthetic-Datasetprocessed_data G!(prop & prop) | F(prop & prop & Fprop) 12
NL-to-LTL-Synthetic-Datasetprocessed_data G!(prop | prop | prop) 12
NL-to-LTL-Synthetic-Datasetprocessed_data G!(prop | prop) 12
NL-to-LTL-Synthetic-Datasetprocessed_data G!(prop | prop) | F((prop | prop) & F(prop & prop)) 12
NL-to-LTL-Synthetic-Datasetprocessed_data G!(prop | prop) | F((prop | prop) & F(prop | prop)) 12
NL-to-LTL-Synthetic-Datasetprocessed_data G!(prop | prop) | F((prop | prop) & Fprop) 12
NL-to-LTL-Synthetic-Datasetprocessed_data G!prop 2
NL-to-LTL-Synthetic-Datasetprocessed_data G!prop | F(prop & F(prop & prop)) 12
NL-to-LTL-Synthetic-Datasetprocessed_data G!prop | F(prop & F(prop | prop)) 12
NL-to-LTL-Synthetic-Datasetprocessed_data G!prop | F(prop & Fprop) 6
NL-to-LTL-Synthetic-Datasetprocessed_data G((prop & prop) -> F(prop & prop)) 12
NL-to-LTL-Synthetic-Datasetprocessed_data G((prop & prop) -> F(prop | prop)) 12
NL-to-LTL-Synthetic-Datasetprocessed_data G((prop & prop) -> Fprop) 12
NL-to-LTL-Synthetic-Datasetprocessed_data G((prop & prop) -> G!(prop & prop)) 12
NL-to-LTL-Synthetic-Datasetprocessed_data G((prop & prop) -> G!(prop | prop)) 12
NL-to-LTL-Synthetic-Datasetprocessed_data G((prop & prop) -> G(prop & prop)) 12
NL-to-LTL-Synthetic-Datasetprocessed_data G((prop & prop) -> G(prop | prop)) 12
NL-to-LTL-Synthetic-Datasetprocessed_data G((prop & prop) -> Gprop) 12
NL-to-LTL-Synthetic-Datasetprocessed_data G((prop | prop) -> F(prop & prop)) 12
NL-to-LTL-Synthetic-Datasetprocessed_data G((prop | prop) -> F(prop | prop)) 12
NL-to-LTL-Synthetic-Datasetprocessed_data G((prop | prop) -> Fprop) 12
NL-to-LTL-Synthetic-Datasetprocessed_data G((prop | prop) -> G!(prop & prop)) 12
NL-to-LTL-Synthetic-Datasetprocessed_data G((prop | prop) -> G!(prop | prop)) 12
NL-to-LTL-Synthetic-Datasetprocessed_data G((prop | prop) -> G(prop & prop)) 12
NL-to-LTL-Synthetic-Datasetprocessed_data G((prop | prop) -> G(prop | prop)) 12
NL-to-LTL-Synthetic-Datasetprocessed_data G((prop | prop) -> Gprop) 12
NL-to-LTL-Synthetic-Datasetprocessed_data G(prop & prop & prop) 12
NL-to-LTL-Synthetic-Datasetprocessed_data G(prop & prop) 12
NL-to-LTL-Synthetic-Datasetprocessed_data G(prop -> F(prop & prop)) 12
NL-to-LTL-Synthetic-Datasetprocessed_data G(prop -> F(prop | prop)) 12
NL-to-LTL-Synthetic-Datasetprocessed_data G(prop -> Fprop) 12
NL-to-LTL-Synthetic-Datasetprocessed_data G(prop -> G(prop & prop)) 12
NL-to-LTL-Synthetic-Datasetprocessed_data G(prop -> G(prop -> Fprop)) 12
NL-to-LTL-Synthetic-Datasetprocessed_data G(prop -> G(prop | prop)) 12
NL-to-LTL-Synthetic-Datasetprocessed_data G(prop | prop | prop) 12
NL-to-LTL-Synthetic-Datasetprocessed_data G(prop | prop) 12
NL-to-LTL-Synthetic-Datasetprocessed_data Gprop 12
lifted_data_pureLTL.jsonl !((prop & prop) U prop) 2
lifted_data_pureLTL.jsonl !((prop -> prop) U prop) 4
lifted_data_pureLTL.jsonl !(Fprop & Fprop) 6
lifted_data_pureLTL.jsonl !(Fprop & GFprop) 2
lifted_data_pureLTL.jsonl !(Fprop U Fprop) 1
lifted_data_pureLTL.jsonl !(Fprop | Fprop) 5
lifted_data_pureLTL.jsonl !(prop & !prop) 2
lifted_data_pureLTL.jsonl !(prop & (prop U prop)) 4
lifted_data_pureLTL.jsonl !(prop & Fprop) 7
lifted_data_pureLTL.jsonl !(prop & GFprop) 2
lifted_data_pureLTL.jsonl !(prop & Gprop) 2
lifted_data_pureLTL.jsonl !(prop & prop & prop) 2
lifted_data_pureLTL.jsonl !(prop & prop) 2
lifted_data_pureLTL.jsonl !(prop & prop) -> prop 12
lifted_data_pureLTL.jsonl !(prop & prop) U prop 6
lifted_data_pureLTL.jsonl !(prop -> prop) -> prop 4
lifted_data_pureLTL.jsonl !(prop -> prop) U prop 2
lifted_data_pureLTL.jsonl !(prop <-> (prop & prop)) 2
lifted_data_pureLTL.jsonl !(prop <-> (prop U prop)) 5
lifted_data_pureLTL.jsonl !(prop <-> prop) -> prop 12
lifted_data_pureLTL.jsonl !(prop <-> prop) U prop 2
lifted_data_pureLTL.jsonl !(prop U Fprop) 5
lifted_data_pureLTL.jsonl !(prop U GFprop) 1
lifted_data_pureLTL.jsonl !(prop U prop) 2
lifted_data_pureLTL.jsonl !(prop U prop) -> prop 8
lifted_data_pureLTL.jsonl !(prop | !prop) 3
lifted_data_pureLTL.jsonl !(prop | (prop & prop)) 3
lifted_data_pureLTL.jsonl !(prop | (prop U prop)) 6
lifted_data_pureLTL.jsonl !(prop | Fprop) 9
lifted_data_pureLTL.jsonl !(prop | G!prop) 1
lifted_data_pureLTL.jsonl !(prop | GFprop) 2
lifted_data_pureLTL.jsonl !(prop | Gprop) 1
lifted_data_pureLTL.jsonl !(prop | prop) 2
lifted_data_pureLTL.jsonl !(prop | prop) -> prop 12
lifted_data_pureLTL.jsonl !(prop | prop) U prop 4
lifted_data_pureLTL.jsonl !Fprop -> Fprop 1
lifted_data_pureLTL.jsonl !Fprop -> prop 2
lifted_data_pureLTL.jsonl !prop 1
lifted_data_pureLTL.jsonl !prop & (prop -> prop) 12
lifted_data_pureLTL.jsonl !prop & (prop <-> Fprop) 2
lifted_data_pureLTL.jsonl !prop & (prop <-> prop) 12
lifted_data_pureLTL.jsonl !prop & (prop U prop) 12
lifted_data_pureLTL.jsonl !prop & (prop | Gprop) 1
lifted_data_pureLTL.jsonl !prop & (prop | prop) 12
lifted_data_pureLTL.jsonl !prop & prop 2
lifted_data_pureLTL.jsonl !prop & prop & (prop -> prop) 5
lifted_data_pureLTL.jsonl !prop & prop & Gprop 1
lifted_data_pureLTL.jsonl !prop & prop & prop 7
lifted_data_pureLTL.jsonl !prop -> (Gprop -> prop) 1
lifted_data_pureLTL.jsonl !prop -> (prop & Fprop) 1
lifted_data_pureLTL.jsonl !prop -> (prop & Gprop) 1
lifted_data_pureLTL.jsonl !prop -> (prop & prop) 12
lifted_data_pureLTL.jsonl !prop -> (prop -> prop) 12
lifted_data_pureLTL.jsonl !prop -> (prop <-> prop) 8
lifted_data_pureLTL.jsonl !prop -> (prop U prop) 12
lifted_data_pureLTL.jsonl !prop -> (prop | Fprop) 1
lifted_data_pureLTL.jsonl !prop -> (prop | Gprop) 1
lifted_data_pureLTL.jsonl !prop -> (prop | prop) 12
lifted_data_pureLTL.jsonl !prop -> Fprop 5
lifted_data_pureLTL.jsonl !prop -> prop 4
lifted_data_pureLTL.jsonl !prop <-> (prop & Fprop) 3
lifted_data_pureLTL.jsonl !prop <-> (prop & Gprop) 3
lifted_data_pureLTL.jsonl !prop <-> (prop & prop) 12
lifted_data_pureLTL.jsonl !prop <-> (prop -> prop) 12
lifted_data_pureLTL.jsonl !prop <-> (prop <-> prop) 12
lifted_data_pureLTL.jsonl !prop <-> (prop U prop) 12
lifted_data_pureLTL.jsonl !prop <-> (prop | prop) 12
lifted_data_pureLTL.jsonl !prop <-> prop 1
lifted_data_pureLTL.jsonl !prop U (prop & prop) 12
lifted_data_pureLTL.jsonl !prop U (prop -> prop) 8
lifted_data_pureLTL.jsonl !prop U (prop <-> prop) 12
lifted_data_pureLTL.jsonl !prop U (prop | prop) 12
lifted_data_pureLTL.jsonl !prop U prop 11
lifted_data_pureLTL.jsonl !prop | (Fprop -> prop) 2
lifted_data_pureLTL.jsonl !prop | (Gprop -> prop) 6
lifted_data_pureLTL.jsonl !prop | (prop & Gprop) 2
lifted_data_pureLTL.jsonl !prop | (prop & prop) 12
lifted_data_pureLTL.jsonl !prop | (prop -> prop) 12
lifted_data_pureLTL.jsonl !prop | (prop <-> Fprop) 4
lifted_data_pureLTL.jsonl !prop | (prop <-> Gprop) 2
lifted_data_pureLTL.jsonl !prop | (prop <-> prop) 12
lifted_data_pureLTL.jsonl !prop | (prop U prop) 12
lifted_data_pureLTL.jsonl !prop | prop | Fprop 2
lifted_data_pureLTL.jsonl !prop | prop | Gprop 1
lifted_data_pureLTL.jsonl !prop | prop | prop 12
lifted_data_pureLTL.jsonl (!prop & prop) -> Fprop 1
lifted_data_pureLTL.jsonl (!prop & prop) -> Gprop 1
lifted_data_pureLTL.jsonl (!prop & prop) -> prop 3
lifted_data_pureLTL.jsonl (!prop & prop) <-> Gprop 1
lifted_data_pureLTL.jsonl (!prop & prop) | Fprop 1
lifted_data_pureLTL.jsonl (!prop & prop) | Gprop 2
lifted_data_pureLTL.jsonl (!prop -> !prop) & Gprop 4
lifted_data_pureLTL.jsonl (!prop -> prop) & Fprop 3
lifted_data_pureLTL.jsonl (!prop -> prop) & Gprop 3
lifted_data_pureLTL.jsonl (!prop -> prop) -> Fprop 2
lifted_data_pureLTL.jsonl (!prop -> prop) <-> Fprop 1
lifted_data_pureLTL.jsonl (!prop -> prop) <-> Gprop 1
lifted_data_pureLTL.jsonl (!prop -> prop) U prop 2
lifted_data_pureLTL.jsonl (!prop -> prop) | (prop -> (prop | prop)) 5
lifted_data_pureLTL.jsonl (!prop -> prop) | Fprop 3
lifted_data_pureLTL.jsonl (!prop <-> prop) & Fprop 1
lifted_data_pureLTL.jsonl (!prop <-> prop) & Gprop 1
lifted_data_pureLTL.jsonl (!prop <-> prop) -> Fprop 1
lifted_data_pureLTL.jsonl (!prop <-> prop) -> prop 2
lifted_data_pureLTL.jsonl (!prop <-> prop) U prop 3
lifted_data_pureLTL.jsonl (!prop <-> prop) | Fprop 1
lifted_data_pureLTL.jsonl (!prop <-> prop) | Gprop 3
lifted_data_pureLTL.jsonl (!prop U prop) -> prop 2
lifted_data_pureLTL.jsonl (!prop | prop) & Gprop 1
lifted_data_pureLTL.jsonl (!prop | prop) -> prop 1
lifted_data_pureLTL.jsonl (!prop | prop) <-> Fprop 1
lifted_data_pureLTL.jsonl (!prop | prop) <-> Gprop 2
lifted_data_pureLTL.jsonl (!prop | prop) U prop 2
lifted_data_pureLTL.jsonl ((prop & prop) -> (prop U !prop)) & (prop U !prop) 5
lifted_data_pureLTL.jsonl ((prop & prop) -> (prop U prop)) & (prop U !prop) 5
lifted_data_pureLTL.jsonl ((prop & prop) -> prop) -> prop 2
lifted_data_pureLTL.jsonl ((prop & prop) U prop) -> prop 4
lifted_data_pureLTL.jsonl ((prop -> prop) -> prop) -> prop 6
lifted_data_pureLTL.jsonl ((prop -> prop) -> prop) U prop 2
lifted_data_pureLTL.jsonl ((prop -> prop) U prop) -> prop 2
lifted_data_pureLTL.jsonl ((prop <-> prop) -> prop) -> prop 4
lifted_data_pureLTL.jsonl ((prop <-> prop) -> prop) U prop 4
lifted_data_pureLTL.jsonl ((prop <-> prop) U prop) -> prop 12
lifted_data_pureLTL.jsonl ((prop U prop) -> prop) -> prop 3
lifted_data_pureLTL.jsonl ((prop | prop) -> prop) -> prop 4
lifted_data_pureLTL.jsonl ((prop | prop) U prop) -> prop 12
lifted_data_pureLTL.jsonl (F!prop -> prop) -> prop 2
lifted_data_pureLTL.jsonl (Fprop -> prop) -> !prop 1
lifted_data_pureLTL.jsonl (Fprop -> prop) -> prop 2
lifted_data_pureLTL.jsonl (Gprop -> prop) -> !prop 3
lifted_data_pureLTL.jsonl (prop & !prop) -> Fprop 3
lifted_data_pureLTL.jsonl (prop & !prop) -> Gprop 4
lifted_data_pureLTL.jsonl (prop & !prop) -> prop 3
lifted_data_pureLTL.jsonl (prop & !prop) <-> Fprop 1
lifted_data_pureLTL.jsonl (prop & !prop) <-> Gprop 3
lifted_data_pureLTL.jsonl (prop & !prop) | Fprop 4
lifted_data_pureLTL.jsonl (prop & !prop) | Gprop 1
lifted_data_pureLTL.jsonl (prop & (prop -> prop)) -> prop 8
lifted_data_pureLTL.jsonl (prop & (prop <-> prop)) -> prop 12
lifted_data_pureLTL.jsonl (prop & (prop <-> prop)) U prop 4
lifted_data_pureLTL.jsonl (prop & (prop U prop)) -> prop 6
lifted_data_pureLTL.jsonl (prop & (prop | prop)) -> prop 8
lifted_data_pureLTL.jsonl (prop & (prop | prop)) U prop 2
lifted_data_pureLTL.jsonl (prop & Gprop) -> !prop 1
lifted_data_pureLTL.jsonl (prop & prop & prop) -> prop 4
lifted_data_pureLTL.jsonl (prop & prop & prop) U prop 4
lifted_data_pureLTL.jsonl (prop & prop) -> !prop 12
lifted_data_pureLTL.jsonl (prop & prop) -> ((prop & prop) U prop) 2
lifted_data_pureLTL.jsonl (prop & prop) -> (prop & prop) 7
lifted_data_pureLTL.jsonl (prop & prop) -> (prop -> (prop & prop & prop)) 2
lifted_data_pureLTL.jsonl (prop & prop) -> (prop -> prop) 7
lifted_data_pureLTL.jsonl (prop & prop) -> (prop <-> prop) 6
lifted_data_pureLTL.jsonl (prop & prop) -> (prop U prop) 7
lifted_data_pureLTL.jsonl (prop & prop) -> (prop | prop) 10
lifted_data_pureLTL.jsonl (prop & prop) -> Fprop 12
lifted_data_pureLTL.jsonl (prop & prop) -> Gprop 12
lifted_data_pureLTL.jsonl (prop & prop) -> prop 8
lifted_data_pureLTL.jsonl (prop & prop) <-> (prop & prop) 4
lifted_data_pureLTL.jsonl (prop & prop) <-> (prop U prop) 12
lifted_data_pureLTL.jsonl (prop & prop) <-> (prop | prop) 12
lifted_data_pureLTL.jsonl (prop & prop) <-> Fprop 12
lifted_data_pureLTL.jsonl (prop & prop) <-> Gprop 12
lifted_data_pureLTL.jsonl (prop & prop) U !prop 12
lifted_data_pureLTL.jsonl (prop & prop) U (prop & prop) 7
lifted_data_pureLTL.jsonl (prop & prop) U (prop -> prop) 6
lifted_data_pureLTL.jsonl (prop & prop) U (prop <-> prop) 9
lifted_data_pureLTL.jsonl (prop & prop) U (prop | prop) 4
lifted_data_pureLTL.jsonl (prop & prop) U prop 2
lifted_data_pureLTL.jsonl (prop & prop) | (prop & prop) 5
lifted_data_pureLTL.jsonl (prop & prop) | (prop U prop) 7
lifted_data_pureLTL.jsonl (prop & prop) | Fprop 12
lifted_data_pureLTL.jsonl (prop & prop) | Gprop 12
lifted_data_pureLTL.jsonl (prop -> !prop) & Gprop 3
lifted_data_pureLTL.jsonl (prop -> prop) & (prop -> prop) 10
lifted_data_pureLTL.jsonl (prop -> prop) & (prop <-> prop) 12
lifted_data_pureLTL.jsonl (prop -> prop) & (prop U prop) 12
lifted_data_pureLTL.jsonl (prop -> prop) & (prop | prop) 6
lifted_data_pureLTL.jsonl (prop -> prop) & Fprop 12
lifted_data_pureLTL.jsonl (prop -> prop) & G(prop & prop) 2
lifted_data_pureLTL.jsonl (prop -> prop) & Gprop 12
lifted_data_pureLTL.jsonl (prop -> prop) -> !prop 12
lifted_data_pureLTL.jsonl (prop -> prop) -> (prop & prop) 2
lifted_data_pureLTL.jsonl (prop -> prop) -> (prop -> prop) 4
lifted_data_pureLTL.jsonl (prop -> prop) -> (prop <-> prop) 10
lifted_data_pureLTL.jsonl (prop -> prop) -> (prop | prop) 6
lifted_data_pureLTL.jsonl (prop -> prop) -> Fprop 12
lifted_data_pureLTL.jsonl (prop -> prop) -> Gprop 12
lifted_data_pureLTL.jsonl (prop -> prop) -> prop 4
lifted_data_pureLTL.jsonl (prop -> prop) <-> (prop & prop) 12
lifted_data_pureLTL.jsonl (prop -> prop) <-> (prop -> prop) 8
lifted_data_pureLTL.jsonl (prop -> prop) <-> (prop <-> prop) 7
lifted_data_pureLTL.jsonl (prop -> prop) <-> (prop U prop) 11
lifted_data_pureLTL.jsonl (prop -> prop) <-> (prop | prop) 12
lifted_data_pureLTL.jsonl (prop -> prop) <-> Fprop 12
lifted_data_pureLTL.jsonl (prop -> prop) <-> Gprop 12
lifted_data_pureLTL.jsonl (prop -> prop) U !prop 12
lifted_data_pureLTL.jsonl (prop -> prop) U (prop & prop) 4
lifted_data_pureLTL.jsonl (prop -> prop) U (prop -> prop) 11
lifted_data_pureLTL.jsonl (prop -> prop) U (prop <-> prop) 12
lifted_data_pureLTL.jsonl (prop -> prop) U (prop | prop) 12
lifted_data_pureLTL.jsonl (prop -> prop) | (prop & prop) 12
lifted_data_pureLTL.jsonl (prop -> prop) | (prop -> prop) 2
lifted_data_pureLTL.jsonl (prop -> prop) | (prop <-> prop) 5
lifted_data_pureLTL.jsonl (prop -> prop) | (prop U prop) 12
lifted_data_pureLTL.jsonl (prop -> prop) | Fprop 12
lifted_data_pureLTL.jsonl (prop -> prop) | Gprop 12
lifted_data_pureLTL.jsonl (prop <-> !prop) & Gprop 1
lifted_data_pureLTL.jsonl (prop <-> !prop) -> prop 1
lifted_data_pureLTL.jsonl (prop <-> !prop) U prop 5
lifted_data_pureLTL.jsonl (prop <-> !prop) | Fprop 2
lifted_data_pureLTL.jsonl (prop <-> (prop & prop)) -> prop 3
lifted_data_pureLTL.jsonl (prop <-> (prop & prop)) U prop 6
lifted_data_pureLTL.jsonl (prop <-> (prop -> prop)) -> prop 6
lifted_data_pureLTL.jsonl (prop <-> (prop U prop)) -> prop 2
lifted_data_pureLTL.jsonl (prop <-> (prop | prop)) -> prop 6
lifted_data_pureLTL.jsonl (prop <-> (prop | prop)) U prop 6
lifted_data_pureLTL.jsonl (prop <-> Fprop) -> !prop 1
lifted_data_pureLTL.jsonl (prop <-> prop) & (prop -> prop) 12
lifted_data_pureLTL.jsonl (prop <-> prop) & (prop <-> prop) 6
lifted_data_pureLTL.jsonl (prop <-> prop) & (prop U prop) 9
lifted_data_pureLTL.jsonl (prop <-> prop) & (prop | prop) 11
lifted_data_pureLTL.jsonl (prop <-> prop) & Fprop 12
lifted_data_pureLTL.jsonl (prop <-> prop) & Gprop 12
lifted_data_pureLTL.jsonl (prop <-> prop) -> !prop 12
lifted_data_pureLTL.jsonl (prop <-> prop) -> (prop & prop) 5
lifted_data_pureLTL.jsonl (prop <-> prop) -> (prop -> prop) 8
lifted_data_pureLTL.jsonl (prop <-> prop) -> (prop <-> prop) 6
lifted_data_pureLTL.jsonl (prop <-> prop) -> (prop U prop) 10
lifted_data_pureLTL.jsonl (prop <-> prop) -> (prop | prop) 5
lifted_data_pureLTL.jsonl (prop <-> prop) -> Fprop 12
lifted_data_pureLTL.jsonl (prop <-> prop) -> Gprop 12
lifted_data_pureLTL.jsonl (prop <-> prop) -> prop 8
lifted_data_pureLTL.jsonl (prop <-> prop) <-> (prop U prop) 5
lifted_data_pureLTL.jsonl (prop <-> prop) <-> (prop | prop) 4
lifted_data_pureLTL.jsonl (prop <-> prop) <-> Fprop 9
lifted_data_pureLTL.jsonl (prop <-> prop) <-> Gprop 10
lifted_data_pureLTL.jsonl (prop <-> prop) U !prop 12
lifted_data_pureLTL.jsonl (prop <-> prop) U (prop & prop) 1
lifted_data_pureLTL.jsonl (prop <-> prop) U (prop -> prop) 9
lifted_data_pureLTL.jsonl (prop <-> prop) U (prop <-> prop) 2
lifted_data_pureLTL.jsonl (prop <-> prop) U (prop | prop) 2
lifted_data_pureLTL.jsonl (prop <-> prop) | (prop & prop) 12
lifted_data_pureLTL.jsonl (prop <-> prop) | (prop -> prop) 7
lifted_data_pureLTL.jsonl (prop <-> prop) | (prop <-> prop) 5
lifted_data_pureLTL.jsonl (prop <-> prop) | (prop U prop) 12
lifted_data_pureLTL.jsonl (prop <-> prop) | Fprop 12
lifted_data_pureLTL.jsonl (prop <-> prop) | Gprop 12
lifted_data_pureLTL.jsonl (prop U prop) -> !prop 12
lifted_data_pureLTL.jsonl (prop U prop) -> (prop & prop) 5
lifted_data_pureLTL.jsonl (prop U prop) -> (prop -> prop) 12
lifted_data_pureLTL.jsonl (prop U prop) -> (prop <-> prop) 4
lifted_data_pureLTL.jsonl (prop U prop) -> (prop | prop) 12
lifted_data_pureLTL.jsonl (prop U prop) -> prop 6
lifted_data_pureLTL.jsonl (prop U prop) U prop 3

In [29]:
aaa

6316

In [25]:
for datasource in first_batch:
    with open(f'First_Batch/per_source/{datasource}_first_batch.csv', 'w') as g:
        g.write(f'{'NL'};{'LTL'};{'APs'};{'lifted_lifted'};{'source'}')
        g.write("\n")
        for formula in first_batch[datasource]:
            for triple in first_batch[datasource][formula]:
                g.write(f'{triple[0].replace(";", " ")};{triple[1]};{triple[2]};{triple[3]};{triple[4]}')
                g.write("\n")

In [26]:

with open(f'First_Batch/all_first_batch.csv', 'w') as g:
    for datasource in first_batch:
        g.write(f'{'NL'};{'LTL'};{'APs'};{'lifted_lifted'};{'source'}')
        g.write("\n")
        for formula in first_batch[datasource]:
            for triple in first_batch[datasource][formula]:
                g.write(f'{triple[0].replace(";", " ")};{triple[1]};{triple[2]};{triple[3]};{triple[4]}')
                g.write("\n")

In [8]:

for datasource in nested_dict:
    for formula in nested_dict[datasource]:
        for triple in nested_dict[datasource][formula]:
            nl_text = triple[0]
            if ";" in nl_text:
                print(nl_text)

If (prop_1), then do (prop_3); or else, don't (prop_2) .
If (prop_2), then do (prop_3); or else, don't (prop_1) .
If (prop_3) is true, then (prop_4) should be true as well; and if (prop_2) is true if and only if (prop_1) should be true; these two should be equivalent .
If (prop_3) is true, then (prop_2) should be true as well; and if (prop_4) is true if and only if (prop_1) should be true; these two should be equivalent .
If (prop_1), then do (prop_4); or if (prop_2), then do (prop_3) .
If (prop_2), then do (prop_4); or if (prop_1), then do (prop_3) .
If ( prop_4 ) and ( prop_3 ) are detected then implies ( prop_2 ) should happen ; or else if ( prop_1 ) is detected .
If ( prop_1 ) and ( prop_4 ) are detected then implies ( prop_2 ) should happen ; or else if ( prop_3 ) is detected .

In [16]:
first_batch['VLTL-Bench_New']

{'!G!(prop & Xprop)': [('Look for the giraffe should always hold, with at most a two-step grace period for recovery.',
   '!G!("search(giraffe)" & X"search(giraffe)")',
   '[\'"search(giraffe)"\']'),
  ('Provide assistance to the safe_hostile should always hold, with at most a two-step grace period for recovery.',
   '!G!("deliver_aid(safe_hostile)" & X"deliver_aid(safe_hostile)")',
   '[\'"deliver_aid(safe_hostile)"\']'),
  ('Stay away from the inactive_fire_source should always hold, with at most a two-step grace period for recovery.',
   '!G!("avoid(inactive_fire_source)" & X"avoid(inactive_fire_source)")',
   '[\'"avoid(inactive_fire_source)"\']'),
  ('Deliver the handbag to the loading_dock should always hold, with at most a two-step grace period for recovery.',
   '!G!("deliver(handbag,loading_dock)" & X"deliver(handbag,loading_dock)")',
   '[\'"deliver(handbag,loading_dock)"\']'),
  ('Locate the toothbrush should always hold, with at most a two-step grace period for recovery.',
   '!G!("search(toothbrush)" & X"search(toothbrush)")',
   '[\'"search(toothbrush)"\']'),
  ('Begin recording the motorcycle on south_10th_street should always hold, with at most a two-step grace period for recovery.',
   '!G!("record(motorcycle,south_10th_street)" & X"record(motorcycle,south_10th_street)")',
   '[\'"record(motorcycle,south_10th_street)"\']'),
  ('Take a picture of debris should always hold, with at most a two-step grace period for recovery.',
   '!G!("photo(debris)" & X"photo(debris)")',
   '[\'"photo(debris)"\']'),
  ('Begin recording the collision on northwest_4th_street should always hold, with at most a two-step grace period for recovery.',
   '!G!("record(collision,northwest_4th_street)" & X"record(collision,northwest_4th_street)")',
   '[\'"record(collision,northwest_4th_street)"\']'),
  ('Deliver aid to the injured_victim should always hold, with at most a two-step grace period for recovery.',
   '!G!("deliver_aid(injured_victim)" & X"deliver_aid(injured_victim)")',
   '[\'"deliver_aid(injured_victim)"\']'),
  ('Find the cake should always hold, with at most a two-step grace period for recovery.',
   '!G!("search(cake)" & X"search(cake)")',
   '[\'"search(cake)"\']'),
  ('Take a photo of the person on northwest_6th_street should always hold, with at most a two-step grace period for recovery.',
   '!G!("photo(person,northwest_6th_street)" & X"photo(person,northwest_6th_street)")',
   '[\'"photo(person,northwest_6th_street)"\']'),
  ('Transport the chair to the loading_dock should always hold, with at most a two-step grace period for recovery.',
   '!G!("deliver(chair,loading_dock)" & X"deliver(chair,loading_dock)")',
   '[\'"deliver(chair,loading_dock)"\']')],
 '!prop U prop': [('Photograph safe_person can only happen after returning home.',
   '!"photo(safe_person)" U go_home',
   '[\'go_home\', \'"photo(safe_person)"\']'),
  ('Update light_west yellow can only happen after change light_south green.',
   '!"change(light_west,yellow)" U "change(light_south,green)"',
   '[\'"change(light_west,yellow)"\', \'"change(light_south,green)"\']'),
  ('Call for help can only happen after change light_east red.',
   '!get_help U "change(light_east,red)"',
   '[\'get_help\', \'"change(light_east,red)"\']'),
  ('Record flood can only happen after calling for help.',
   '!"record(flood)" U get_help',
   '[\'get_help\', \'"record(flood)"\']'),
  ('Call for help can only happen after idleing.',
   '!get_help U idle',
   "['get_help', 'idle']"),
  ('Communicate with the safe_hostile can only happen after requesting assistance.',
   '!"communicate(safe_hostile)" U get_help',
   '[\'get_help\', \'"communicate(safe_hostile)"\']'),
  ('Provide assistance to the injured_rescuer can only happen after calling for help.',
   '!"deliver_aid(injured_rescuer)" U get_help',
   '[\'get_help\', \'"deliver_aid(injured_rescuer)"\']'),
  ('Record debris can only happen after geting help.',
   '!"record(debris)" U get_help',
   '[\'get_help\', \'"record(debris)"\']'),
  ('Deliver the parking_meter to the loading_dock can only happen after picking up the baseball_bat.',
   '!"deliver(parking_meter,loading_dock)" U "pickup(baseball_bat)"',
   '[\'"deliver(parking_meter,loading_dock)"\', \'"pickup(baseball_bat)"\']'),
  ('Take a picture of safe_rescuer can only happen after avoid the inactive_unstable_beam.',
   '!"photo(safe_rescuer)" U "avoid(inactive_unstable_beam)"',
   '[\'"photo(safe_rescuer)"\', \'"avoid(inactive_unstable_beam)"\']'),
  ('Record the pedestrian on southwest_4th_avenue can only happen after photoing the car on south_8th_avenue.',
   '!"record(pedestrian,southwest_4th_avenue)" U "photo(car,south_8th_avenue)"',
   '[\'"record(pedestrian,southwest_4th_avenue)"\', \'"photo(car,south_8th_avenue)"\']'),
  ('Photograph the person on northeast_4th_street can only happen after calling for help.',
   '!"photo(person,northeast_4th_street)" U get_help',
   '[\'get_help\', \'"photo(person,northeast_4th_street)"\']')],
 '(prop U prop) | Gprop': [('Take a photo of the vehicle on south_9th_street must hold until change light_west yellow does, or else photo the vehicle on south_9th_street holds forever.',
   '("photo(vehicle,south_9th_street)" U "change(light_west,yellow)") | G"photo(vehicle,south_9th_street)"',
   '[\'"change(light_west,yellow)"\', \'"photo(vehicle,south_9th_street)"\']'),
  ('Take a photo of safe_victim must hold until staying away from the inactive_fire_source does, or else photo safe_victim holds forever.',
   '("photo(safe_victim)" U "avoid(inactive_fire_source)") | G"photo(safe_victim)"',
   '[\'"photo(safe_victim)"\', \'"avoid(inactive_fire_source)"\']'),
  ('You must avoid the impending_debris must hold until deliver_aid the safe_hostile does, or else avoid the impending_debris holds forever.',
   '("avoid(impending_debris)" U "deliver_aid(safe_hostile)") | G"avoid(impending_debris)"',
   '[\'"deliver_aid(safe_hostile)"\', \'"avoid(impending_debris)"\']'),
  ('Pick up the person must hold until calling for help does, or else pickup the person holds forever.',
   '("pickup(person)" U get_help) | G"pickup(person)"',
   '[\'get_help\', \'"pickup(person)"\']'),
  ('Take a photo of flood must hold until talking to the injured_hostile does, or else photo flood holds forever.',
   '("photo(flood)" U "communicate(injured_hostile)") | G"photo(flood)"',
   '[\'"photo(flood)"\', \'"communicate(injured_hostile)"\']'),
  ('Return home must hold until photo safe_victim does, or else go_home holds forever.',
   '(go_home U "photo(safe_victim)") | Ggo_home',
   '[\'"photo(safe_victim)"\', \'go_home\']'),
  ('You must pickup the hair-drier must hold until picking up the zebra does, or else pickup the hair-drier holds forever.',
   '("pickup(hair-drier)" U "pickup(zebra)") | G"pickup(hair-drier)"',
   '[\'"pickup(zebra)"\', \'"pickup(hair-drier)"\']'),
  ('Take a photo of safe_rescuer must hold until get_help does, or else photo safe_rescuer holds forever.',
   '("photo(safe_rescuer)" U get_help) | G"photo(safe_rescuer)"',
   '[\'get_help\', \'"photo(safe_rescuer)"\']'),
  ('Return home must hold until avoid the active_debris does, or else go_home holds forever.',
   '(go_home U "avoid(active_debris)") | Ggo_home',
   '[\'go_home\', \'"avoid(active_debris)"\']'),
  ('Get help must hold until delivering the book to the shelf does, or else get_help holds forever.',
   '(get_help U "deliver(book,shelf)") | Gget_help',
   '[\'get_help\', \'"deliver(book,shelf)"\']'),
  ('Update light_south yellow must hold until recording the person on east_1st_avenue does, or else change light_south yellow holds forever.',
   '("change(light_south,yellow)" U "record(person,east_1st_avenue)") | G"change(light_south,yellow)"',
   '[\'"change(light_south,yellow)"\', \'"record(person,east_1st_avenue)"\']'),
  ('The system must avoid the nearest_flood must hold until returning to base does, or else avoid the nearest_flood holds forever.',
   '("avoid(nearest_flood)" U go_home) | G"avoid(nearest_flood)"',
   '[\'go_home\', \'"avoid(nearest_flood)"\']')],
 'F!prop': [('Our agent must eventually, avoid going back to base.',
   'F!go_home',
   "['go_home']"),
  ('This controller must eventually, avoid begining recording the cyclist on northwest_2nd_avenue.',
   'F!"record(cyclist,northwest_2nd_avenue)"',
   '[\'"record(cyclist,northwest_2nd_avenue)"\']'),
  ('The robot must eventually, avoid establishing communication with the injured_hostile.',
   'F!"communicate(injured_hostile)"',
   '[\'"communicate(injured_hostile)"\']'),
  ('The system must eventually, avoid begining recording the cyclist on north_1st_street.',
   'F!"record(cyclist,north_1st_street)"',
   '[\'"record(cyclist,north_1st_street)"\']'),
  ('You must eventually, avoid photoing gas_leak.',
   'F!"photo(gas_leak)"',
   '[\'"photo(gas_leak)"\']'),
  ('The robot must eventually, avoid pickuping the carrot.',
   'F!"pickup(carrot)"',
   '[\'"pickup(carrot)"\']'),
  ('The robot must eventually, avoid change light_east green.',
   'F!"change(light_east,green)"',
   '[\'"change(light_east,green)"\']'),
  ('You must eventually, avoid change light_east red.',
   'F!"change(light_east,red)"',
   '[\'"change(light_east,red)"\']'),
  ('The system must eventually, avoid searching the sports_ball.',
   'F!"search(sports_ball)"',
   '[\'"search(sports_ball)"\']'),
  ('This controller must eventually, avoid photoing flood.',
   'F!"photo(flood)"',
   '[\'"photo(flood)"\']'),
  ('This controller must eventually, avoid change light_north yellow.',
   'F!"change(light_north,yellow)"',
   '[\'"change(light_north,yellow)"\']'),
  ('The system must eventually, avoid droping off the surfboard to the loading_dock.',
   'F!"deliver(surfboard,loading_dock)"',
   '[\'"deliver(surfboard,loading_dock)"\']')],
 'F(prop & prop)': [('You must Eventually, both go_home and deliver_aid the injured_hostile hold simultaneously.',
   'F("deliver_aid(injured_hostile)" & go_home)',
   '[\'go_home\', \'"deliver_aid(injured_hostile)"\']'),
  ('You must eventually get_help and pickup the cell_phone.',
   'F(get_help & "pickup(cell_phone)")',
   '[\'get_help\', \'"pickup(cell_phone)"\']'),
  ('The robot must eventually deliver_aid the safe_hostile and go_home.',
   'F("deliver_aid(safe_hostile)" & go_home)',
   '[\'go_home\', \'"deliver_aid(safe_hostile)"\']'),
  ('Our agent must eventually deliver the sports_ball to the shelf and idle.',
   'F("deliver(sports_ball,shelf)" & idle)',
   '[\'idle\', \'"deliver(sports_ball,shelf)"\']'),
  ('You must Eventually, both photo fire_source and record injured_rescuer hold simultaneously.',
   'F("photo(fire_source)" & "record(injured_rescuer)")',
   '[\'"record(injured_rescuer)"\', \'"photo(fire_source)"\']'),
  ('The system must Eventually, both idle and pickup the toaster hold simultaneously.',
   'F(idle & "pickup(toaster)")',
   '[\'idle\', \'"pickup(toaster)"\']'),
  ('The system must eventually record the car on east_2nd_street and photo the pedestrian on southeast_4th_street.',
   'F("photo(pedestrian,southeast_4th_street)" & "record(car,east_2nd_street)")',
   '[\'"photo(pedestrian,southeast_4th_street)"\', \'"record(car,east_2nd_street)"\']'),
  ('The robot must eventually search the sandwich and pickup the banana.',
   'F("pickup(banana)" & "search(sandwich)")',
   '[\'"pickup(banana)"\', \'"search(sandwich)"\']'),
  ('The robot must Eventually, both get_help and pickup the tie hold simultaneously.',
   'F(get_help & "pickup(tie)")',
   '[\'get_help\', \'"pickup(tie)"\']'),
  ('This controller must Eventually, both change light_east red and photo the car on west_2nd_street hold simultaneously.',
   'F("change(light_east,red)" & "photo(car,west_2nd_street)")',
   '[\'"change(light_east,red)"\', \'"photo(car,west_2nd_street)"\']'),
  ('The system must eventually photo the cyclist on southwest_7th_street and record the cyclist on northwest_3rd_street.',
   'F("photo(cyclist,southwest_7th_street)" & "record(cyclist,northwest_3rd_street)")',
   '[\'"photo(cyclist,southwest_7th_street)"\', \'"record(cyclist,northwest_3rd_street)"\']'),
  ('This controller must Eventually, both pickup the bear and idle hold simultaneously.',
   'F(idle & "pickup(bear)")',
   '[\'idle\', \'"pickup(bear)"\']')],
 'F(prop | prop)': [('The robot must eventually search the bed or search the vase.',
   'F("search(bed)" | "search(vase)")',
   '[\'"search(bed)"\', \'"search(vase)"\']'),
  ('The robot must eventually change light_west red or photo the vehicle on southwest_9th_street.',
   'F("change(light_west,red)" | "photo(vehicle,southwest_9th_street)")',
   '[\'"change(light_west,red)"\', \'"photo(vehicle,southwest_9th_street)"\']'),
  ('The system must eventually idle or deliver the sandwich to the loading_dock.',
   'F("deliver(sandwich,loading_dock)" | idle)',
   '[\'idle\', \'"deliver(sandwich,loading_dock)"\']'),
  ('You must eventually avoid the probable_gas_leak or photo unstable_beam.',
   'F("avoid(probable_gas_leak)" | "photo(unstable_beam)")',
   '[\'"avoid(probable_gas_leak)"\', \'"photo(unstable_beam)"\']'),
  ('You must eventually record the collision on north_3rd_avenue or change light_south yellow.',
   'F("change(light_south,yellow)" | "record(collision,north_3rd_avenue)")',
   '[\'"change(light_south,yellow)"\', \'"record(collision,north_3rd_avenue)"\']'),
  ('You must eventually deliver the toaster to the loading_dock or pickup the cell_phone.',
   'F("deliver(toaster,loading_dock)" | "pickup(cell_phone)")',
   '[\'"pickup(cell_phone)"\', \'"deliver(toaster,loading_dock)"\']'),
  ('Our agent must eventually change light_east red or photo the pedestrian on northwest_4th_avenue.',
   'F("change(light_east,red)" | "photo(pedestrian,northwest_4th_avenue)")',
   '[\'"change(light_east,red)"\', \'"photo(pedestrian,northwest_4th_avenue)"\']'),
  ('You must eventually change light_east green or record the person on northeast_6th_avenue.',
   'F("change(light_east,green)" | "record(person,northeast_6th_avenue)")',
   '[\'"change(light_east,green)"\', \'"record(person,northeast_6th_avenue)"\']'),
  ('The system must eventually pickup the vase or pickup the tie.',
   'F("pickup(tie)" | "pickup(vase)")',
   '[\'"pickup(vase)"\', \'"pickup(tie)"\']'),
  ('The system must eventually idle or search the teddy-bear.',
   'F(idle | "search(teddy-bear)")',
   '[\'idle\', \'"search(teddy-bear)"\']'),
  ('The robot must eventually change light_north yellow or get_help.',
   'F("change(light_north,yellow)" | get_help)',
   '[\'get_help\', \'"change(light_north,yellow)"\']'),
  ('The system must eventually get_help or change light_west red.',
   'F("change(light_west,red)" | get_help)',
   '[\'get_help\', \'"change(light_west,red)"\']')],
 'FG!prop': [('From some point onwards, photo the motorcycle on south_9th_street never occurs again.',
   'FG!"photo(motorcycle,south_9th_street)"',
   '[\'"photo(motorcycle,south_9th_street)"\']'),
  ('From some point onwards, photo the pedestrian on south_3rd_street never occurs again.',
   'FG!"photo(pedestrian,south_3rd_street)"',
   '[\'"photo(pedestrian,south_3rd_street)"\']'),
  ('From some point onwards, search the zebra never occurs again.',
   'FG!"search(zebra)"',
   '[\'"search(zebra)"\']'),
  ('From some point onwards, search the bench never occurs again.',
   'FG!"search(bench)"',
   '[\'"search(bench)"\']'),
  ('From some point onwards, search the cell_phone never occurs again.',
   'FG!"search(cell_phone)"',
   '[\'"search(cell_phone)"\']'),
  ('From some point onwards, deliver the horse to the shelf never occurs again.',
   'FG!"deliver(horse,shelf)"',
   '[\'"deliver(horse,shelf)"\']'),
  ('From some point onwards, record injured_rescuer never occurs again.',
   'FG!"record(injured_rescuer)"',
   '[\'"record(injured_rescuer)"\']'),
  ('From some point onwards, record the collision on northwest_10th_street never occurs again.',
   'FG!"record(collision,northwest_10th_street)"',
   '[\'"record(collision,northwest_10th_street)"\']'),
  ('From some point onwards, avoid the nearest_flood never occurs again.',
   'FG!"avoid(nearest_flood)"',
   '[\'"avoid(nearest_flood)"\']'),
  ('From some point onwards, change light_east green never occurs again.',
   'FG!"change(light_east,green)"',
   '[\'"change(light_east,green)"\']'),
  ('From some point onwards, search the giraffe never occurs again.',
   'FG!"search(giraffe)"',
   '[\'"search(giraffe)"\']'),
  ('From some point onwards, record the car on northeast_4th_street never occurs again.',
   'FG!"record(car,northeast_4th_street)"',
   '[\'"record(car,northeast_4th_street)"\']')],
 'Fprop & Fprop': [('Take a picture of gas_leak and avoid the active gas_leak will each happen at some point.',
   'F"photo(gas_leak)" & F"avoid(active_gas_leak)"',
   '[\'"photo(gas_leak)"\', \'"avoid(active_gas_leak)"\']'),
  ('Photograph injured_rescuer and avoid the impending_gas_leak will each happen at some point.',
   'F"photo(injured_rescuer)" & F"avoid(impending_gas_leak)"',
   '[\'"avoid(impending_gas_leak)"\', \'"photo(injured_rescuer)"\']'),
  ('Take a video of the person on east_8th_street and change light_east green will each happen at some point.',
   'F"record(person,east_8th_street)" & F"change(light_east,green)"',
   '[\'"record(person,east_8th_street)"\', \'"change(light_east,green)"\']'),
  ('Photograph the collision on north_9th_street and change light_north yellow will each happen at some point.',
   'F"photo(collision,north_9th_street)" & F"change(light_north,yellow)"',
   '[\'"change(light_north,yellow)"\', \'"photo(collision,north_9th_street)"\']'),
  ('Establish communication with the injured_victim and go_home will each happen at some point.',
   'F"communicate(injured_victim)" & Fgo_home',
   '[\'"communicate(injured_victim)"\', \'go_home\']'),
  ('Deliver the toilet to the loading_dock and deliver the banana to the shelf will each happen at some point.',
   'F"deliver(toilet,loading_dock)" & F"deliver(banana,shelf)"',
   '[\'"deliver(banana,shelf)"\', \'"deliver(toilet,loading_dock)"\']'),
  ('Search for the bus and get_help will each happen at some point.',
   'F"search(bus)" & Fget_help',
   '[\'get_help\', \'"search(bus)"\']'),
  ('Begin recording injured_person and record flood will each happen at some point.',
   'F"record(injured_person)" & F"record(flood)"',
   '[\'"record(injured_person)"\', \'"record(flood)"\']'),
  ('Go home and avoid the impending_debris will each happen at some point.',
   'Fgo_home & F"avoid(impending_debris)"',
   '[\'go_home\', \'"avoid(impending_debris)"\']'),
  ('Deliver aid to the injured_hostile and photo injured_civilian will each happen at some point.',
   'F"deliver_aid(injured_hostile)" & F"photo(injured_civilian)"',
   '[\'"deliver_aid(injured_hostile)"\', \'"photo(injured_civilian)"\']'),
  ('Request assistance and record gas_leak will each happen at some point.',
   'Fget_help & F"record(gas_leak)"',
   '[\'get_help\', \'"record(gas_leak)"\']'),
  ('Record unstable_beam and photo safe_civilian will each happen at some point.',
   'F"record(unstable_beam)" & F"photo(safe_civilian)"',
   '[\'"photo(safe_civilian)"\', \'"record(unstable_beam)"\']')],
 'Fprop -> (!prop U (!prop & prop))': [('If deliver the sink to the loading_dock ever holds, pickup the scissors must have held beforehand.',
   'F"deliver(sink,loading_dock)" -> (!"deliver(sink,loading_dock)" U (!"deliver(sink,loading_dock)" & "pickup(scissors)"))',
   '[\'"pickup(scissors)"\', \'"deliver(sink,loading_dock)"\']'),
  ('If deliver the book to the loading_dock ever holds, pickup the toothbrush must have held beforehand.',
   'F"deliver(book,loading_dock)" -> (!"deliver(book,loading_dock)" U (!"deliver(book,loading_dock)" & "pickup(toothbrush)"))',
   '[\'"pickup(toothbrush)"\', \'"deliver(book,loading_dock)"\']'),
  ('If communicate the injured_rescuer ever holds, deliver_aid the injured_victim must have held beforehand.',